Impl
awnzl/myip pull request #1
Opened 2021-06-15 16:08 UTC by awnzl

2021-06-18 12:53 UTC, sladonia requested changes

2021-06-18 12:53 UTC, sladonia commented on cmd/myip/cfg.go
> +	var allProviders, shortAllProviders bool
как-то это не очень получается, если у тебя разные переменные на short и длинное имя. Или используй библиотеку, которая может вычитывать в одну переменную или оставляй только одну опцию (short или long). А иначе для меня как для клиента непонятно поведение, если я буду обе опции задавать.

2021-06-18 12:53 UTC, sladonia commented on cmd/myip/cfg.go
> +		os.Exit(0)
os.Exit может быть в функции main, но не здесь. Пользователь глядя на сигнатуру функции `func parseConfig() Config` не может даже предположить что эта функция может завершить всю программу. Правильный интерфейс будет `func parseConfig() (Config, error)` - не смог спарсить - вернул ошибку, а в main принял решение о завершении программы.

2021-06-18 12:53 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +	finder := &Finder{
адреса провайдеров не должны быть захардкожены в службе Find, провайдеры должны передаваться в конструкторе

2021-06-18 12:53 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +type Provider struct {
неподходящее название для этой структуры. Темболее что у тебя в этом неймспейсе уже есть providers, которые имеют другой смысл. По смыслу здесь может быть название Result, или что-то другое на твое усмотрение

2021-06-18 12:53 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +	if useAllProviders {
тут излишне две реализации allProvidersResponse и anyProviderResponse. Это может быть один метод, который возвращает рузельтирующий канал. А там где ты вычитываешь из канала - принимаешь решение, вычитывать только один результат или дожидаться всех

2021-06-18 12:53 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +		wg := new(sync.WaitGroup)
с WaitGroup совсем напутал. Вот пример из официальной документации. Он предельно близок к тому что тебе нужно сделать: https://golang.org/pkg/sync/#example_WaitGroup

2021-06-18 12:53 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +	bytes, _ := io.ReadAll(src)
почему игнорим ошибку? вполне себе может быть ошибка

2021-06-18 12:53 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +	select {
здесь селект не нужен. Ты же выполняешь `req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)`
если контекст закенселится - запрос прервется и вернется ошибка context.Canceled

2021-06-18 12:53 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +			out <- Provider{URL: url, Response: timedOut}
не стоит так перемешивать ответы с ошибками. Правельнее чтобы метод  requestIP возвращал ошибку

2021-06-26 12:51 UTC, awnzl commented on cmd/myip/cfg.go
> +	var allProviders, shortAllProviders bool
Прежде всего - имея короткую и длинную версию опций я реализую POSIX требование к синтаксису аргументов командной строки.
Что до "две переменные на аргумент" vs "дополнительная зависимость в программе", то мне кажется, что две переменные - не такое уж и зло, тем более, что наверняка под капотом любой такой библиотеки будет ещё вагон переменых...
По части ясности поведения - это да, надо подкрутить в usage информацию, т.к. такое поведение в целом оставляется на откуп разработчика и нужна ясность...

2021-06-29 11:00 UTC, sladonia reviewed
в целом хорошо. Давай теперь добавим тот провайдер что json возвращает, а не текст

2021-06-29 11:00 UTC, sladonia commented on cmd/myip/cfg.go
> +	pflag.IntVarP(&timeout, "timeout", "t", 5, "")
`pflag.Duration` парсит из стринги типа `1h5s`

2021-06-29 11:00 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +	select {
remove test block)

2021-06-29 11:00 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +func (f *Finder) FindIp(useAllProviders bool, timeout int) ([]Response, error) {
здесь бы предложил в одном цикле обрабатывать ответ, в смысле чтобы не вычитывать сначала один
```
func (f *Finder) FindIp(useAllProviders bool, timeout int) ([]Response, error) {
	timeoutCtx, cancel := context.WithTimeout(context.Background(), time.Duration(timeout)*time.Second)
	defer cancel()

	var responses []Response

	for resp := range f.requestProviders(timeoutCtx) {
		if resp.Error != nil {
			/// log error
			continue
		}

		responses = append(responses, resp.Response)
		
		if !useAllProviders {
			break
		}
	}

	return responses, nil
}
```

2021-06-29 11:00 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +		return Response{}, http.ErrBodyNotAllowed
тут скорее правильно свою ошибку сделать, а не из пакета http

2021-06-29 11:00 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +func (f *Finder) requestProviders(timeoutCtx context.Context) <-chan ResponseWithError {
просто ctx, этот метод не обязан знать что ему контекст с таймаутом прокидывают

2021-06-29 11:00 UTC, sladonia commented on internal/ipfinder/ipfinder.go
> +func (f *Finder) FindIp(useAllProviders bool, timeout int) ([]Response, error) {
лучше сюда не таймаут прокидывать, а контекст. пусть клиент этого метода сам решает какой контекст ему нужен

```
func (f *Finder) FindIp(ctx context.Context, useAllProviders bool) ([]Response, error) {
```

2021-06-30 09:29 UTC, awnzl commented on cmd/myip/cfg.go
> +	pflag.IntVarP(&timeout, "timeout", "t", 5, "")
тогда придется даже простой таймаут в секунду писать с указанием величины времени, например  `1s`, что мне кажется неудобным, и не очень характерным для типично интерфейса утилит командной строки... ))

2021-07-02 14:53 UTC, sladonia approved these changes
🥳

2021-07-02 14:53 UTC, sladonia commented on cmd/myip/cfg.go
> +	Timeout      float64
duration. можно парсить внутри parseConfig()

2021-07-02 14:53 UTC, sladonia commented on internal/writer/writer.go
> +func (p *Writer) Write(providers []client.Response) {
responses

2021-07-07 14:53 UTC, merged